FROM ubuntu:18.04
RUN apt-get update && apt-get install -y python3

RUN apt-get update && apt-get install -y iputils-ping

WORKDIR /my_script

RUN apt-get update && apt-get install -y python3

COPY . .
